### ISSUE TITLE
Safe List Updates with DynamoDB

### ISSUE THREAD

**Issue by robzhu** [build-on-aws/content#305]
# Amazonian Contributors

If you are an Amazonian, please find the BuildOn.AWS wiki for more information on how to propose content. Any GitHub issues submitted here will be closed.

# Community Contributors

January 27, 2023 - BuildOn.AWS content contributions are invite-only right now as we gather feedback and refine the publication processes and documentation. Star or watch [this repository](https://github.com/build-on-aws/content/) for updates as we open this up to more community authors in the coming months.

## Interested in writing content for BuildOn.AWS? Yay! We're so happy you're here.

1. Review the [Author Quick Start](https://github.com/build-on-aws/content/blob/main/AUTHOR_QUICK_START.md) before submitting your proposal to get an idea of the content we're looking for.
2. Set your proposed content title to the title of this issue.
3. Fill out the information below.

### What is the title of the content you're proposing?
Safe List Updates with DynamoDB

### Describe your content, including takeaways for the reader, in three to four sentences.
When modifying a list attribute on a DynamoDB document, we need to take extra steps to achieve correctness and concurrency. I discuss several solutions in this post.

### What theme is your content related to?
Databases, NoSQL

### When can you provide your first draft of content by?
5/10

### What are 2-3 links to previous written content you have published?
https://medium.com/@robzhu
https://updateloop.dev/

**Comment by robzhu** [comment]
What is the next step?

**Comment by cobusbernard** [comment]
@robzhu : Next steps documented in the Author quickstart guide: https://github.com/build-on-aws/content/blob/main/AUTHOR_QUICK_START.md#2-proposal-review

**Comment by bketelsen** [comment]
closed by #426 
@robzhu thanks for your contribution! Your article is live now https://www.buildon.aws/posts/ddb-safe-list-updates
