### ISSUE TITLE
Building a multi-region serverless IoT system

### ISSUE THREAD

**Issue by JimmyDqv** [build-on-aws/content#516]
### What is the title of the content you're proposing?
Building a multi-region serverless IoT system

### Describe your content, including takeaways for the reader, in three to four sentences.
How to build and create a multi-region serverless IoT system where clients can connect to any region. Deep dive into IoT Core setup and how to synchronise certificates across regions, how to store data in a global way and how to access the data. Serverless data ingestion and processing in an event-driven architecture.

### What theme is your content related to?
Serverless, IoT, Event-Driven Architecture

### When can you provide your first draft of content by?
Mid August

### What are 2-3 links to previous written content you have published?
[Running VS Code server on AWS](https://dev.to/aws-builders/running-vs-code-server-on-aws-51h6)
[Serverless patterns](https://dev.to/aws-builders/serverless-patterns-4439)
[Serverless voice with Amazon Polly](https://dev.to/aws-builders/serverless-voice-with-amazon-polly-2lfd)

**Comment by bketelsen** [comment]
This proposal looks great! Please proceed when you are ready.

**Comment by bketelsen** [comment]
Thank you for your interest in the BuildOn.AWS Community Authoring Pilot.

 
Step 1: [Read the Author Quick Start Guide](https://github.com/build-on-aws/content/blob/main/AUTHOR_QUICK_START.md) – note that in the publishing process listed on that page we’ve already done steps 0, 1, and 2.
Step 2: [Write your first draft](https://github.com/build-on-aws/content/blob/main/AUTHOR_QUICK_START.md#3-write-your-first-draft) – you’ll need to create a fork of the content repository, create a new git branch for your article, then submit a pull request with your first draft. The linked guide has all the details.
Step 3: [Submit your Pull Request](https://github.com/build-on-aws/content/blob/main/AUTHOR_QUICK_START.md#3-write-your-first-draft) – our team will get a notification that your article is ready for review and it will be added to our editorial queue. We’ll check the syntax of the markdown and other technical details, and we’ll read the article to make sure it meets our publication guidelines.  After your submit the pull request, you’ll get a link to a preview version of the article so you can check it for formatting and other errors. The link will come in a comment to your pull request. Don’t share this link, it’s not the final publication link, just a place for you to review what you’ve written before it’s published.
Step 4: Publication! – when the review is completed, we’ll merge the pull request and the publication will be live in just a few moments.
 
Our team will be on standby to answer any questions you have along the way.  Here are some resources that may be helpful:
 
[FAQ](https://github.com/build-on-aws/content/blob/main/FAQ.md)
[Code of Conduct](https://github.com/build-on-aws/content/blob/main/CODE_OF_CONDUCT.md)
[Quick Start Guide](https://github.com/build-on-aws/content/blob/main/AUTHOR_QUICK_START.md)
 
Please reach out if you have any questions or anything is unclear. You’re the first to go through this process, so you might find gaps in our documentation or bumps in the process… let us know so we can fix it!

**Comment by JimmyDqv** [comment]
Pull-Request created: https://github.com/build-on-aws/content/pull/634

**Comment by bketelsen** [comment]
closed by #634

**Comment by bketelsen** [comment]
Thank you for your post @JimmyDqv!
