### ISSUE TITLE
Using Amazon SageMaker to Optimize Compilation and Training for GPT-2 Model 

### ISSUE THREAD

**Issue by hanyun2019** [build-on-aws/content#529]
### What is the title of the content you're proposing?
Using Amazon SageMaker to Optimize Compilation and Training for GPT-2 Model 

### Describe your content, including takeaways for the reader, in three to four sentences.
SageMaker Training Compiler is a capability of SageMaker that makes these hard-to-implement optimizations to reduce training time on GPU instances. In this post, we'll guide you to use Hugging Face's transformers and datasets libraries with Amazon SageMaker Training Compiler to train the gpt-2 model on the Stanford Sentiment Treebank v2 (SST2) dataset. 

### What theme is your content related to?
Containers, Data, AI/ML, GenAI.

### When can you provide your first draft of content by?
The first draft has been completed already.

### What are 2-3 links to previous written content you have published?
A New World 0f Generative AI - Part 1: Overview 
https://dev.amazoncloud.cn/column/article/6413095e3d950b57b3f9f63d

A New World 0f Generative AI - Part 2: Papers Illustration
https://dev.amazoncloud.cn/column/article/641c329888a713631101349a

A New World 0f Generative AI - Part 3: LLMs Overview
https://mp.weixin.qq.com/s/wmZKu7aE1rAQ7JTJEbRUAg

A New World 0f Generative AI - Part 4: LLMs with SageMaker in Practice
https://mp.weixin.qq.com/s/I7ATuuGiD235ZTbhomowbw

**Comment by bketelsen** [comment]
yes, please! sounds like a great article.
