### ISSUE TITLE
Building a Amplify Flutter for Web Page using a Serverless CDK Backend in Typescript with AppSync Merged APIs

### ISSUE THREAD

**Issue by Lock128** [build-on-aws/content#537]
### What is the title of the content you're proposing?
Building a Amplify Flutter for Web Page using a Serverless CDK Backend in Typescript with AppSync Merged APIs

### Describe your content, including takeaways for the reader, in three to four sentences.
I would love to contribute a post that gives a "starting point" for building out an application that looks similar to our community builders speaker directory - see the overview post we had here: https://dev.to/aws-builders/presenting-aws-speakers-directory-an-ai-hackathon-project-19je
As part of this post, we would take a deeper look into the architeture and how to integrate with Amplify SDK for Flutter as well as. the Serverless, AppSync backed backend.

### What theme is your content related to?
Web development, Serverless

### When can you provide your first draft of content by?
End of july/mid august

### What are 2-3 links to previous written content you have published?
My personal blog is at lockhead.info, but i cross-post to https://dev.to/lockhead and the community builders ORG there

**Comment by bketelsen** [comment]
Great topic, we'd love to see it.

**Comment by Lock128** [comment]
I am late with the deliverable here - will get back to you with a new planned date.
