### ISSUE TITLE
Start your projects with a CI/CD pipeline to deliver value right from the start of your project

### ISSUE THREAD

**Issue by Lock128** [build-on-aws/content#538]
### What is the title of the content you're proposing?
Start your projects with a CI/CD pipeline to deliver value right from the start of your project

### Describe your content, including takeaways for the reader, in three to four sentences.
The post will be explaining what CI/CD is and means. It will go into details around how software developers produce "business values" by writing code and about how a CI/CD pipeline that is 100% automated ensures to be able to delivery value quickly.
I will also discuss the impact of being able to quickly push production changes and briefly introduce the concept of feature flagging.
In the latter part of the post I want to use the CodeCatalyst blue prints as an example/showcase on how this could look like.
Depending on when we release this, we can also reference the open source project "projen-pipelines" as a place to watch for future updates.

### What theme is your content related to?
Automation, Other.

### When can you provide your first draft of content by?
Depends on if the other article gets selected too - mid august 23?

### What are 2-3 links to previous written content you have published?
My personal blog is at https://www.lockhead.info, but i cross-post to https://dev.to/lockhead and the community builders ORG there

**Comment by bketelsen** [comment]
this sounds great, we'd love to see this article.

**Comment by bketelsen** [comment]
Thank you for your interest in the BuildOn.AWS Community Authoring Pilot.
 
 
Step 1: [Read the Author Quick Start Guide](https://github.com/build-on-aws/content/blob/main/AUTHOR_QUICK_START.md) – note that in the publishing process listed on that page we’ve already done steps 0, 1, and 2.
Step 2: [Write your first draft](https://github.com/build-on-aws/content/blob/main/AUTHOR_QUICK_START.md#3-write-your-first-draft) – you’ll need to create a fork of the content repository, create a new git branch for your article, then submit a pull request with your first draft. The linked guide has all the details.
Step 3: [Submit your Pull Request](https://github.com/build-on-aws/content/blob/main/AUTHOR_QUICK_START.md#3-write-your-first-draft) – our team will get a notification that your article is ready for review and it will be added to our editorial queue. We’ll check the syntax of the markdown and other technical details, and we’ll read the article to make sure it meets our publication guidelines.  After your submit the pull request, you’ll get a link to a preview version of the article so you can check it for formatting and other errors. The link will come in a comment to your pull request. Don’t share this link, it’s not the final publication link, just a place for you to review what you’ve written before it’s published.
Step 4: Publication! – when the review is completed, we’ll merge the pull request and the publication will be live in just a few moments.
 
Our team will be on standby to answer any questions you have along the way.  Here are some resources that may be helpful:
 
[FAQ](https://github.com/build-on-aws/content/blob/main/FAQ.md)
[Code of Conduct](https://github.com/build-on-aws/content/blob/main/CODE_OF_CONDUCT.md)
[Quick Start Guide](https://github.com/build-on-aws/content/blob/main/AUTHOR_QUICK_START.md)
 
Please reach out if you have any questions or anything is unclear. You’re the first to go through this process, so you might find gaps in our documentation or bumps in the process… let us know so we can fix it!

**Comment by Lock128** [comment]
I am late with the deliverable here - will get back to you with a new planned date.
