### ISSUE TITLE
A Tool to Validate AWS IoT Rules SQL Statements 

### ISSUE THREAD

**Issue by alinadima** [build-on-aws/content#560]
# Amazonian Contributors

If you are an Amazonian, please find the Community.AWS wiki for more information on how to propose content. Any GitHub issues submitted here will be closed.

# Community Contributors

January 27, 2023 - Community.AWS content contributions are invite-only right now as we gather feedback and refine the publication processes and documentation. Star or watch [this repository](https://github.com/build-on-aws/content/) for updates as we open this up to more community authors in the coming months.

## Interested in writing content for Community.AWS? Yay! We're so happy you're here.

1. Review the [Author Quick Start](https://github.com/build-on-aws/content/blob/main/AUTHOR_QUICK_START.md) before submitting your proposal to get an idea of the content we're looking for.
2. Set your proposed content title to the title of this issue.
3. Fill out the information below.

### What is the title of the content you're proposing?
A Tool to Validate AWS IoT Rules SQL Statements

### Describe your content, including takeaways for the reader, in three to four sentences.
Rules Engine is a feature in AWS IoT Core that allows engineers to filter, decode, and process IoT device data and route this data to 15+ AWS and third-party services. AWS IoT Core Rules Engine currently has support for over 70 distinct SQL functions which can be used in either SELECT or WHERE clauses, 14 distinct operators which can be used in either SELECT or WHERE clauses, all JSON data types, specifying Literal objects in the SELECT and WHERE clauses, case statements, JSON extensions, substitution templates and nested object queries and more.

In this post, we explore how to validate AWS IoT Core Rules Engine Rules SQL Statements, by introducing a validation tool which:
- Encapsulates the heavy lifting of creating, configuring and cleaning up the AWS resources needed to create, run and validate IoT Rule SQL payload transformations.
- Enables friction free validation of Rules syntax and payload transformations.
- Provides an easily extensible library of sample SQL statements, with input payloads and expected output, allowing you to build your own use-cases.

This tool is available on GitHub, [here](https://github.com/aws-iot-builder-tools/validation-tool-for-aws-iot-rules/).

### What theme is your content related to?
IoT

### When can you provide your first draft of content by?
This is a re-publish. Content is available here: https://dev.to/iotbuilders/a-tool-to-validate-aws-iot-rules-sql-statements-jg

### What are 2-3 links to previous written content you have published?
https://dev.to/fay_ette

**Comment by bketelsen** [comment]
approve

**Comment by bketelsen** [comment]
closed by #573
